/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("profile").del();
  await knex("profile").insert([
    {
      id: 1,
      name: "Sarah",
      age: 34,
      bio: "I love to explore new places and try new foods. My favorite trip so far has been to Japan, where I ate the most amazing sushi and saw beautiful cherry blossoms.",
      location_id: 9,
      start_date: "2023-05-01",
      end_date: "2023-05-08",
      avatar_url: "https://randomuser.me/api/portraits/women/31.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 2,
      name: "David",
      age: 27,
      bio: "I am a thrill-seeker and love to try new things. Skydiving is my favorite activity, and I recently went bungee jumping for the first time. I also enjoy hiking and exploring the outdoors.",
      location_id: 12,
      start_date: "2023-06-23",
      end_date: "2023-06-30",
      avatar_url: "https://randomuser.me/api/portraits/men/5.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 3,
      name: "Emily",
      age: 42,
      bio: "I enjoy learning about new cultures and trying new foods. I recently took a trip to Italy, where I learned how to make homemade pasta and visited many beautiful museums and art galleries.",
      location_id: 6,
      start_date: "2023-07-15",
      end_date: "2023-07-22",
      avatar_url: "https://randomuser.me/api/portraits/women/85.jpg",
      isFriend: 0,
      isSwiped: 0,
    },

    {
      id: 4,
      name: "Jasmine",
      age: 25,
      bio: "I love to travel and try new things. My favorite trip so far has been to Thailand, where I went scuba diving and tried many delicious local dishes.",
      location_id: 7,
      start_date: "2023-08-11",
      end_date: "2023-08-18",
      avatar_url: "https://randomuser.me/api/portraits/women/40.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 5,
      name: "Andrew",
      age: 42,
      bio: "I enjoy visiting historic sites and learning about different cultures. I recently took a trip to Greece, where I saw many ancient ruins and enjoyed the beautiful Mediterranean views.",
      location_id: 1,
      start_date: "2023-09-19",
      end_date: "2023-09-26",
      avatar_url: "https://randomuser.me/api/portraits/men/71.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 6,
      name: "Mia",
      age: 31,
      bio: "I love adventure and trying new things. I recently went skydiving for the first time and loved the thrill. I also enjoy hiking and exploring new places.",
      location_id: 13,
      start_date: "2023-10-04",
      end_date: "2023-10-11",
      avatar_url: "https://randomuser.me/api/portraits/women/38.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 7,
      name: "Benjamin",
      age: 56,
      bio: "I love to travel and experience new cultures. My recent trip to Japan was amazing, where I visited ancient temples and tried many delicious foods.",
      location_id: 10,
      start_date: "2023-11-02",
      end_date: "2023-09-11",
      avatar_url: "https://randomuser.me/api/portraits/men/4.jpg",
      isFriend: 0,
      isSwiped: 0,
    },

    {
      id: 8,
      name: "Jasmine",
      age: 25,
      bio: "I love to travel and try new things. My favorite trip so far has been to Thailand, where I went scuba diving and tried many delicious local dishes.",
      location_id: 7,
      start_date: "2023-08-11",
      end_date: "2023-08-18",
      avatar_url: "https://randomuser.me/api/portraits/women/40.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 9,
      name: "Andrew",
      age: 42,
      bio: "I enjoy visiting historic sites and learning about different cultures. I recently took a trip to Greece, where I saw many ancient ruins and enjoyed the beautiful Mediterranean views.",
      location_id: 1,
      start_date: "2023-06-19",
      end_date: "2023-08-26",
      avatar_url: "https://randomuser.me/api/portraits/men/71.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 10,
      name: "Mia",
      age: 31,
      bio: "I love adventure and trying new things. I recently went skydiving for the first time and loved the thrill. I also enjoy hiking and exploring new places.",
      location_id: 13,
      start_date: "2023-04-03",
      end_date: "2023-08-11",
      avatar_url: "https://randomuser.me/api/portraits/women/38.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 11,
      name: "Benjamin",
      age: 56,
      bio: "I love to travel and experience new cultures. My recent trip to Japan was amazing, where I visited ancient temples and tried many delicious foods.",
      location_id: 10,
      start_date: "2023-05-02",
      end_date: " 2023-10-11",
      avatar_url: "https://randomuser.me/api/portraits/men/4.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 12,
      name: "Natalie",
      age: 28,
      bio: "I enjoy exploring the outdoors and experiencing new cultures. I recently took a trip to Peru, where I hiked to Machu Picchu and tried many delicious local dishes.",
      location_id: 1,
      start_date: "2023-06-30",
      end_date: "2023-08-12",
      avatar_url: "https://randomuser.me/api/portraits/women/36.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 13,
      name: "David",
      age: 34,
      bio: "I enjoy traveling to new places and learning about different cultures. My favorite trip so far has been to Iceland, where I saw many beautiful natural sights and tried some traditional Icelandic foods.",
      location_id: 4,
      start_date: "2023-05-14",
      end_date: "2023-06-14",
      avatar_url: "https://randomuser.me/api/portraits/men/64.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 14,
      name: "Sophie",
      age: 27,
      bio: "I love to travel and try new things. My recent trip to Thailand was amazing, where I went elephant trekking and tried many delicious Thai dishes.",
      location_id: 11,
      start_date: "2023-04-13",
      end_date: "2023-06-13",
      avatar_url: "https://randomuser.me/api/portraits/women/19.jpg",
      isFriend: 0,
      isSwiped: 0,
    },

    {
      id: 15,
      name: "Samantha",
      age: 29,
      bio: "I love adventure and exploring new places. My recent trip to New Zealand was amazing, where I went bungee jumping and saw many beautiful natural sights.",
      location_id: 3,
      start_date: "2023-05-17",
      end_date: "2023-07-01",
      avatar_url: "https://randomuser.me/api/portraits/women/86.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 16,
      name: "John",
      age: 50,
      bio: "I love to travel and experience new cultures. My recent trip to Egypt was amazing, where I saw many ancient ruins and learned about the country's fascinating history.",
      location_id: 8,
      start_date: "2023-05-15",
      end_date: "2023-08-01",
      avatar_url: "https://randomuser.me/api/portraits/men/89.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 17,
      name: "Julia",
      age: 24,
      bio: "I enjoy visiting new places and trying new foods. My recent trip to Italy was amazing, where I saw many historic sites and tried many delicious Italian dishes.",
      location_id: 14,
      start_date: "2023-07-19",
      end_date: "2023-09-20",
      avatar_url: "https://randomuser.me/api/portraits/women/64.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 18,
      name: "Alexander",
      age: 39,
      bio: "I love exploring new cities and trying new foods. My favorite place so far has been Tokyo!",
      location_id: 3,
      start_date: "2023-04-30",
      end_date: "2023-06-01",
      avatar_url: "https://randomuser.me/api/portraits/men/1.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 19,
      name: "Madison",
      age: 27,
      bio: "I am a beach bum at heart and love spending my time swimming and surfing. Bali is my favorite place to travel to!",
      location_id: 5,
      start_date: "2023-07-18",
      end_date: "2023-10-30",
      avatar_url: "https://randomuser.me/api/portraits/women/3.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 20,
      name: "Isabella",
      age: 28,
      bio: "I am an adrenaline junkie and love trying extreme sports. My favorite adventure was bungee jumping in New Zealand!",
      location_id: 10,
      start_date: "2023-06-19",
      end_date: "2023-09-14",
      avatar_url: "https://randomuser.me/api/portraits/women/5.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 21,
      name: "Jacob",
      age: 36,
      bio: "I enjoy hiking and camping in national parks. Yellowstone was an amazing experience!",
      location_id: 12,
      start_date: "2023-05-14",
      end_date: "2023-06-15",
      avatar_url: "https://randomuser.me/api/portraits/men/5.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 22,
      name: "Sophia",
      age: 18,
      bio: "I love going on road trips and discovering hidden gems. My favorite drive was along the California coast!",
      location_id: 8,
      start_date: "2023-06-19",
      end_date: "2023-08-15",
      avatar_url: "https://randomuser.me/api/portraits/women/2.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 23,
      name: "Ella",
      age: 33,
      bio: "I am a history buff and enjoy visiting museums and historical sites. My favorite trip so far has been to Rome!",
      location_id: 5,
      start_date: "2023-07-20",
      end_date: "2023-10-13",
      avatar_url: "https://randomuser.me/api/portraits/women/4.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 24,
      name: "Sebastian",
      age: 23,
      bio: "I am a beach bum at heart and love spending my time swimming and surfing. Bali is my favorite place to travel to!",
      location_id: 3,
      start_date: "2023-08-01",
      end_date: "2023-12-01",
      avatar_url: "https://randomuser.me/api/portraits/men/4.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 25,
      name: "Avery",
      age: 47,
      bio: "I enjoy hiking and camping in national parks. Yellowstone was an amazing experience!",
      location_id: 8,
      start_date: "2023-07-26",
      end_date: "2023-09-18",
      avatar_url: "https://randomuser.me/api/portraits/women/1.jpg",
      isFriend: 0,
      isSwiped: 0,
    },

    {
      id: 26,
      name: "Isabella",
      age: 29,
      bio: "I love exploring new cities and trying new foods. My favorite place so far has been Tokyo!",
      location_id: 6,
      start_date: "2023-07-14",
      end_date: "2023-08-30",
      avatar_url: "https://randomuser.me/api/portraits/women/5.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 27,
      name: "Ethan",
      age: 52,
      bio: "I am a history buff and enjoy visiting museums and historical sites. My favorite trip so far has been to Rome!",
      location_id: 7,
      start_date: "2023-06-29",
      end_date: "2023-08-01",
      avatar_url: "https://randomuser.me/api/portraits/men/1.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 28,
      name: "Sophia",
      age: 31,
      bio: "I am an adrenaline junkie and love trying extreme sports. My favorite adventure was bungee jumping in New Zealand!",
      location_id: 11,
      start_date: "2023-07-16",
      end_date: "2023-10-14",
      avatar_url: "https://randomuser.me/api/portraits/women/3.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 29,
      name: "David",
      age: 39,
      bio: "I enjoy hiking and camping in national parks. Yellowstone was an amazing experience!",
      location_id: 4,
      start_date: "2023-07-28",
      end_date: "2023-09-13",
      avatar_url: "https://randomuser.me/api/portraits/men/5.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 30,
      name: "Chloe",
      age: 21,
      bio: "I am a beach bum at heart and love spending my time swimming and surfing. Bali is my favorite place to travel to!",
      location_id: 7,
      start_date: "2023-08-19",
      end_date: "2023-09-13",
      avatar_url: "https://randomuser.me/api/portraits/women/4.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 31,
      name: "Noah",
      age: 28,
      bio: "I am an adrenaline junkie and love trying extreme sports. My favorite adventure was bungee jumping in New Zealand!",
      location_id: 14,
      start_date: "2023-04-13",
      end_date: "2023-08-20",
      avatar_url: "https://randomuser.me/api/portraits/men/3.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 32,
      name: "Madison",
      age: 37,
      bio: "I enjoy hiking and camping in national parks. Yellowstone was an amazing experience!",
      location_id: 12,
      start_date: "2023-05-17",
      end_date: "2023-07-18",
      avatar_url: "https://randomuser.me/api/portraits/women/2.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
    {
      id: 33,
      name: "Alexander",
      age: 50,
      bio: "I love going on road trips and discovering hidden gems. My favorite drive was along the California coast!",
      location_id: 9,
      start_date: "2023-06-01",
      end_date: "2023-09-01",
      avatar_url: "https://randomuser.me/api/portraits/men/4.jpg",
      isFriend: 0,
      isSwiped: 0,
    },
  ]);
};
