/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("profile_event").del();
  await knex("profile_event").insert([
    { profile_id: 1, event_id: 28 },
    { profile_id: 1, event_id: 27 },
    { profile_id: 2, event_id: 35 },
    { profile_id: 2, event_id: 36 },
    { profile_id: 3, event_id: 18 },
    { profile_id: 3, event_id: 17 },
    { profile_id: 4, event_id: 21 },
    { profile_id: 4, event_id: 19 },
    { profile_id: 5, event_id: 4 },
    { profile_id: 5, event_id: 5 },
    { profile_id: 5, event_id: 6 },
    { profile_id: 6, event_id: 38 },
    { profile_id: 6, event_id: 39 },
    { profile_id: 6, event_id: 40 },
    { profile_id: 7, event_id: 29 },
    { profile_id: 7, event_id: 31 },
    { profile_id: 8, event_id: 20 },
    { profile_id: 8, event_id: 19 },
    { profile_id: 9, event_id: 3 },
    { profile_id: 10, event_id: 38 },
    { profile_id: 10, event_id: 39 },
    { profile_id: 10, event_id: 40 },
    { profile_id: 11, event_id: 30 },
    { profile_id: 11, event_id: 31 },
    { profile_id: 12, event_id: 1 },
    { profile_id: 12, event_id: 2 },
    { profile_id: 12, event_id: 3 },
    { profile_id: 13, event_id: 12 },
    { profile_id: 13, event_id: 11 },
    { profile_id: 14, event_id: 34 },
    { profile_id: 14, event_id: 33 },
    { profile_id: 15, event_id: 7 },
    { profile_id: 15, event_id: 6 },
    { profile_id: 16, event_id: 24 },
    { profile_id: 16, event_id: 25 },
    { profile_id: 17, event_id: 42 },
    { profile_id: 17, event_id: 43 },
    { profile_id: 18, event_id: 7 },
    { profile_id: 18, event_id: 6 },
    { profile_id: 18, event_id: 5 },
    { profile_id: 19, event_id: 14 },
    { profile_id: 19, event_id: 15 },
    { profile_id: 20, event_id: 30 },
    { profile_id: 21, event_id: 15 },
    { profile_id: 21, event_id: 35 },
    { profile_id: 22, event_id: 22 },
    { profile_id: 22, event_id: 24 },
    { profile_id: 23, event_id: 10 },
    { profile_id: 23, event_id: 13 },
    { profile_id: 24, event_id: 8 },
    { profile_id: 24, event_id: 9 },
    { profile_id: 25, event_id: 23 },
    { profile_id: 25, event_id: 25 },
    { profile_id: 26, event_id: 16 },
    { profile_id: 26, event_id: 18 },
    { profile_id: 27, event_id: 19 },
    { profile_id: 27, event_id: 21 },
    { profile_id: 28, event_id: 32 },
    { profile_id: 29, event_id: 11 },
    { profile_id: 29, event_id: 12 },
    { profile_id: 30, event_id: 20 },
    { profile_id: 30, event_id: 21 },
    { profile_id: 31, event_id: 43 },
    { profile_id: 31, event_id: 41 },
    { profile_id: 32, event_id: 35 },
    { profile_id: 32, event_id: 37 },
    { profile_id: 33, event_id: 26 },
  ]);
};
